name: Upload Files to Google Drive
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Clear hash file if force update requested
        run: |
          rm -f .drive_sync_hashes.json
          echo "Forcing update of all files"


      - name: Debug environment variables
        run: |
          echo "FOLDER_PATH: $FOLDER_PATH"
          echo "GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}"
          echo "GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      
      # Restore the hash file from cache if it exists
      - name: Restore hash file cache
        uses: actions/cache@v3
        with:
          path: .drive_sync_hashes.json
          key: ${{ runner.os }}-drive-sync-hashes-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-drive-sync-hashes-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cron curl zip
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          
      - name: Grab AWS JS S3 explorer
        run: |
          curl -O https://raw.githubusercontent.com/FortressOne/aws-js-s3-explorer/master/index.html
          mv index.html fortress/maps/
      
      - name: Package BSPs
        run: |
          for package_path in fortress/package/*; do
            ./package_bsps.sh ${package_path}
            rm -rf ${package_path}
          done
      
      - name: Authenticate to Google Drive
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
      
      - name: Upload to Google Drive
        run: |
          python upload_to_drive.py
        env:
          FOLDER_PATH: 'fortress/maps'
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
